"""est_derogation sur etapes_workflow (ecart n4, section 4.4)

Revision ID: 01c3c7004910
Revises: 6e3fd32c1f6e
Create Date: 2026-09-27 21:25:55.883535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01c3c7004910'
down_revision: Union[str, None] = '6e3fd32c1f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ecart corrige manuellement : server_default ajoute, sans quoi cette
    # migration echouerait sur une table etapes_workflow deja peuplee
    # (colonne NOT NULL sans valeur pour les lignes existantes).
    op.add_column(
        'etapes_workflow',
        sa.Column('est_derogation', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etapes_workflow', 'est_derogation')
    # ### end Alembic commands ###
