"""schema initial - 11 entites (CDC section 4 + types_conge et jours_feries)

Revision ID: 056431780b2c
Revises: 
Create Date: 2026-09-14 03:59:46.734144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '056431780b2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnements_webhook',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url_destination', sa.String(length=2048), nullable=False),
    sa.Column('secret_hmac', sa.String(length=255), nullable=False),
    sa.Column('processus', sa.Enum('CONGES', 'NOTES_FRAIS', 'ACHATS', name='type_processus', native_enum=False), nullable=False),
    sa.Column('evenements', sa.JSON(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enveloppes_budgetaires',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service', sa.String(length=120), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('budget_alloue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_consomme', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'exercice', name='uq_enveloppe_service_exercice')
    )
    op.create_table('jours_feries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recurrent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_conge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('taux_acquisition_jours_mois', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('types_demande',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('processus', sa.Enum('CONGES', 'NOTES_FRAIS', 'ACHATS', name='type_processus', native_enum=False), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('schema_champs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processus')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYE', 'MANAGER', 'DRH', 'DIRECTION_FINANCIERE', 'SERVICE_JURIDIQUE', 'DIRECTION_GENERALE', 'CONTROLEUR_DE_GESTION', name='role_utilisateur', native_enum=False), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('demandes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('processus', sa.Enum('CONGES', 'NOTES_FRAIS', 'ACHATS', name='type_processus', native_enum=False), nullable=False),
    sa.Column('demandeur_id', sa.Uuid(), nullable=False),
    sa.Column('initiee_par_id', sa.Uuid(), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.Column('statut_global', sa.Enum('EN_COURS', 'TERMINEE', 'REFUSEE', 'COMPLEMENT_DEMANDE', 'ANNULEE', name='statut_demande', native_enum=False), nullable=False),
    sa.Column('creee_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demandeur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['initiee_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('acteur_id', sa.Uuid(), nullable=True),
    sa.Column('cible_type', sa.String(length=80), nullable=False),
    sa.Column('cible_id', sa.Uuid(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('horodate_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acteur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soldes_conges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('type_conge_id', sa.Uuid(), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('jours_acquis', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('jours_pris', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('solde_jours', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['type_conge_id'], ['types_conge.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id', 'type_conge_id', 'exercice', name='uq_solde_utilisateur_type_exercice')
    )
    op.create_table('etapes_workflow',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('demande_id', sa.Uuid(), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('APPROBATEUR', 'SIGNATAIRE', 'DESTINATAIRE_COPIE', 'RECOMMANDEUR', 'ACCUSE_RECEPTION', 'EXECUTANT_TACHE', 'EDITEUR', name='role_etape', native_enum=False), nullable=False),
    sa.Column('approbateur_attendu_id', sa.Uuid(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'EN_COURS', 'APPROUVE', 'REFUSE', name='statut_etape', native_enum=False), nullable=False),
    sa.Column('jeton_decision', sa.String(length=512), nullable=True),
    sa.Column('jeton_utilise', sa.Boolean(), nullable=False),
    sa.Column('date_reponse', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approbateur_attendu_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieces_jointes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('demande_id', sa.Uuid(), nullable=False),
    sa.Column('nom_original', sa.String(length=255), nullable=False),
    sa.Column('cle_stockage', sa.String(length=512), nullable=False),
    sa.Column('deposee_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieces_jointes')
    op.drop_table('etapes_workflow')
    op.drop_table('soldes_conges')
    op.drop_table('journal_audit')
    op.drop_table('demandes')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_table('types_demande')
    op.drop_table('types_conge')
    op.drop_table('jours_feries')
    op.drop_table('enveloppes_budgetaires')
    op.drop_table('abonnements_webhook')
    # ### end Alembic commands ###
