"""taux_change (plusieurs devises avec conversion)

Revision ID: 398b7b242b1f
Revises: 20e05f709e2a
Create Date: 2026-09-28 15:56:27.542144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '398b7b242b1f'
down_revision: Union[str, None] = '20e05f709e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taux_change',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('taux', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('date_effet', sa.Date(), nullable=False),
    sa.Column('defini_par_id', sa.Uuid(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['defini_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('devise', 'date_effet', name='uq_taux_change_devise_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taux_change')
    # ### end Alembic commands ###
