"""jetons_decision - entite dediee (§9.2-9.3), retrait des champs obsoletes sur etapes_workflow, cible_id nullable sur journal_audit

Revision ID: 51ef1470577f
Revises: 056431780b2c
Create Date: 2026-09-15 20:57:00.424939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51ef1470577f'
down_revision: Union[str, None] = '056431780b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jetons_decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('etape_workflow_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('action_autorisee', sa.String(length=30), nullable=False),
    sa.Column('approbateur_attendu_id', sa.Uuid(), nullable=False),
    sa.Column('expire_a', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilise_a', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoque', sa.Boolean(), nullable=False),
    sa.Column('cree_a', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approbateur_attendu_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['etape_workflow_id'], ['etapes_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jetons_decision_token_hash'), 'jetons_decision', ['token_hash'], unique=True)
    op.drop_column('etapes_workflow', 'jeton_utilise')
    op.drop_column('etapes_workflow', 'jeton_decision')
    # batch_alter_table : portabilite SQLite (utilisee par la suite de tests,
    # section conftest) - PostgreSQL (cible reelle, section 3.3) execute ceci
    # nativement en un simple ALTER COLUMN ... DROP NOT NULL.
    with op.batch_alter_table('journal_audit') as batch_op:
        batch_op.alter_column(
            'cible_id',
            existing_type=sa.Uuid(),
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_audit') as batch_op:
        batch_op.alter_column(
            'cible_id',
            existing_type=sa.Uuid(),
            nullable=False,
        )
    op.add_column('etapes_workflow', sa.Column('jeton_decision', sa.VARCHAR(length=512), nullable=True))
    op.add_column(
        'etapes_workflow',
        sa.Column('jeton_utilise', sa.BOOLEAN(), nullable=False, server_default=sa.false()),
    )
    op.drop_index(op.f('ix_jetons_decision_token_hash'), table_name='jetons_decision')
    op.drop_table('jetons_decision')
    # ### end Alembic commands ###
