"""messages_clarification (ecart n5, section 4.5 - communication bidirectionnelle)

Revision ID: 6e3fd32c1f6e
Revises: ad70367392a7
Create Date: 2026-09-27 21:15:21.678866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e3fd32c1f6e'
down_revision: Union[str, None] = 'ad70367392a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_clarification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('demande_id', sa.Uuid(), nullable=False),
    sa.Column('auteur_id', sa.Uuid(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_clarification')
    # ### end Alembic commands ###
