"""jetons_compte - invitation et reinitialisation de mot de passe (§5), mot_de_passe_hash nullable

Revision ID: 8b72607684ff
Revises: 51ef1470577f
Create Date: 2026-09-16 09:48:38.200401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b72607684ff'
down_revision: Union[str, None] = '51ef1470577f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jetons_compte',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('type_jeton', sa.Enum('INVITATION', 'REINITIALISATION', name='type_jeton_compte', native_enum=False), nullable=False),
    sa.Column('expire_a', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilise_a', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_a', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jetons_compte_token_hash'), 'jetons_compte', ['token_hash'], unique=True)
    # batch_alter_table : portabilite SQLite (suite de tests) - PostgreSQL
    # (cible reelle, section 3.3) execute ceci nativement en un ALTER COLUMN.
    with op.batch_alter_table('utilisateurs') as batch_op:
        batch_op.alter_column(
            'mot_de_passe_hash',
            existing_type=sa.String(length=255),
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs') as batch_op:
        batch_op.alter_column(
            'mot_de_passe_hash',
            existing_type=sa.String(length=255),
            nullable=False,
        )
    op.drop_index(op.f('ix_jetons_compte_token_hash'), table_name='jetons_compte')
    op.drop_table('jetons_compte')
    # ### end Alembic commands ###
