"""reservation solde conges, mouvements_conges, bons_commande et compteur (R17, R21)

Revision ID: a47ac6bac2da
Revises: 398b7b242b1f
Create Date: 2026-09-29 18:25:55.866085

"""
import logging
import re
import uuid
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

journal = logging.getLogger("alembic.runtime.migration")


revision: str = 'a47ac6bac2da'
down_revision: Union[str, None] = '398b7b242b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compteurs_bon_commande',
    sa.Column('exercice', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('dernier_rang', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('exercice')
    )
    op.create_table('bons_commande',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('demande_id', sa.Uuid(), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('rang', sa.Integer(), nullable=False),
    sa.Column('numero_sequentiel', sa.String(length=20), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demande_id'),
    sa.UniqueConstraint('exercice', 'rang', name='uq_bon_commande_exercice_rang'),
    sa.UniqueConstraint('numero_sequentiel')
    )
    op.create_table('mouvements_conges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('type_conge_id', sa.Uuid(), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Uuid(), nullable=True),
    sa.Column('delta', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('motif', sa.Enum('SOLDE_INITIAL', 'ACQUISITION_MENSUELLE', 'RESERVATION', 'LIBERATION_REFUS', 'LIBERATION_ANNULATION', 'LIBERATION_MODIFICATION', 'AJUSTEMENT_MANUEL', name='motif_mouvement_conges', native_enum=False), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.ForeignKeyConstraint(['type_conge_id'], ['types_conge.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouvements_conges_demande_id'), 'mouvements_conges', ['demande_id'], unique=False)
    op.create_index(op.f('ix_mouvements_conges_utilisateur_id'), 'mouvements_conges', ['utilisateur_id'], unique=False)
    op.add_column('soldes_conges', sa.Column('jours_reserves', sa.Numeric(precision=6, scale=1), server_default='0', nullable=False))
    # ### end Alembic commands ###

    _reprendre_soldes_existants()
    _reprendre_numeros_bon_commande_existants()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soldes_conges', 'jours_reserves')
    op.drop_index(op.f('ix_mouvements_conges_utilisateur_id'), table_name='mouvements_conges')
    op.drop_index(op.f('ix_mouvements_conges_demande_id'), table_name='mouvements_conges')
    op.drop_table('mouvements_conges')
    op.drop_table('bons_commande')
    op.drop_table('compteurs_bon_commande')
    # ### end Alembic commands ###


def _reprendre_soldes_existants() -> None:
    """
    Le solde disponible est desormais la somme des mouvements (CDC 11.1). Pour que cette egalite
    tienne des le premier jour, chaque solde deja saisi recoit un mouvement `solde_initial` egal a
    son solde disponible actuel. Les demandes deja en cours n'ont pas de reservation : elles seront
    consommees a leur approbation comme avant (voir verrou_rh.confirmer_reservation).
    """
    connexion = op.get_bind()
    soldes = sa.table(
        "soldes_conges",
        sa.column("utilisateur_id", sa.Uuid()),
        sa.column("type_conge_id", sa.Uuid()),
        sa.column("exercice", sa.Integer()),
        sa.column("solde_jours", sa.Numeric(6, 1)),
    )
    mouvements = sa.table(
        "mouvements_conges",
        sa.column("id", sa.Uuid()),
        sa.column("utilisateur_id", sa.Uuid()),
        sa.column("type_conge_id", sa.Uuid()),
        sa.column("exercice", sa.Integer()),
        sa.column("demande_id", sa.Uuid()),
        sa.column("delta", sa.Numeric(6, 1)),
        sa.column("motif", sa.String()),
        sa.column("cree_le", sa.DateTime(timezone=True)),
    )
    lignes = connexion.execute(sa.select(soldes)).fetchall()
    a_inserer = [
        {
            "id": uuid.uuid4(),
            "utilisateur_id": ligne.utilisateur_id,
            "type_conge_id": ligne.type_conge_id,
            "exercice": ligne.exercice,
            "demande_id": None,
            "delta": ligne.solde_jours,
            "motif": "SOLDE_INITIAL",
            "cree_le": datetime.now(UTC),
        }
        for ligne in lignes
        if ligne.solde_jours
    ]
    if a_inserer:
        connexion.execute(sa.insert(mouvements), a_inserer)


_MOTIF_NUMERO_BC = re.compile(r"^BC-(\d{4})-(\d+)$")


def _reprendre_numeros_bon_commande_existants() -> None:
    """
    Les numeros deja attribues (stockes dans demandes.donnees) sont repris dans `bons_commande` et
    le compteur de chaque exercice est amorce au rang le plus eleve : sans cela, le prochain numero
    pourrait entrer en collision avec un ancien. Si l'ancien calcul par comptage avait produit un
    doublon, seule la premiere occurrence est reprise (les contraintes d'unicite l'exigent) et un
    avertissement est ecrit dans le journal de migration.
    """
    connexion = op.get_bind()
    demandes = sa.table(
        "demandes",
        sa.column("id", sa.Uuid()),
        sa.column("processus", sa.String()),
        sa.column("statut_global", sa.String()),
        sa.column("donnees", sa.JSON()),
        sa.column("creee_le", sa.DateTime(timezone=True)),
    )
    bons = sa.table(
        "bons_commande",
        sa.column("id", sa.Uuid()),
        sa.column("demande_id", sa.Uuid()),
        sa.column("exercice", sa.Integer()),
        sa.column("rang", sa.Integer()),
        sa.column("numero_sequentiel", sa.String()),
        sa.column("cree_le", sa.DateTime(timezone=True)),
    )
    compteurs = sa.table(
        "compteurs_bon_commande",
        sa.column("exercice", sa.Integer()),
        sa.column("dernier_rang", sa.Integer()),
    )
    lignes = connexion.execute(
        sa.select(demandes.c.id, demandes.c.donnees, demandes.c.creee_le)
        .where(demandes.c.processus == "ACHATS", demandes.c.statut_global == "TERMINEE")
        .order_by(demandes.c.creee_le)
    ).fetchall()

    numeros_vus: set[str] = set()
    rangs_vus: set[tuple[int, int]] = set()
    max_par_exercice: dict[int, int] = {}
    a_inserer = []
    for ligne in lignes:
        donnees = ligne.donnees
        if isinstance(donnees, str):
            import json

            donnees = json.loads(donnees)
        numero = (donnees or {}).get("numero_bc")
        correspondance = _MOTIF_NUMERO_BC.match(numero or "")
        if not correspondance:
            continue
        exercice, rang = int(correspondance.group(1)), int(correspondance.group(2))
        max_par_exercice[exercice] = max(max_par_exercice.get(exercice, 0), rang)
        if numero in numeros_vus or (exercice, rang) in rangs_vus:
            journal.warning("Numero de bon de commande deja utilise, non repris : %s (demande %s)", numero, ligne.id)
            continue
        numeros_vus.add(numero)
        rangs_vus.add((exercice, rang))
        a_inserer.append(
            {
                "id": uuid.uuid4(), "demande_id": ligne.id, "exercice": exercice, "rang": rang,
                "numero_sequentiel": numero, "cree_le": ligne.creee_le or datetime.now(UTC),
            }
        )
    if a_inserer:
        connexion.execute(sa.insert(bons), a_inserer)
    if max_par_exercice:
        connexion.execute(
            sa.insert(compteurs),
            [{"exercice": e, "dernier_rang": r} for e, r in max_par_exercice.items()],
        )
