"""revoque sur jetons_compte - renvoi d'invitation et relance de decision (ecart du test reel)

Revision ID: a9e52d92e9a5
Revises: 8b72607684ff
Create Date: 2026-09-17 22:22:43.961531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9e52d92e9a5'
down_revision: Union[str, None] = '8b72607684ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'jetons_compte',
        sa.Column('revoque', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jetons_compte', 'revoque')
    # ### end Alembic commands ###
