"""signature_cle_stockage sur etapes_workflow (role signataire, section 8)

Revision ID: ad70367392a7
Revises: a9e52d92e9a5
Create Date: 2026-09-27 15:54:49.254828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad70367392a7'
down_revision: Union[str, None] = 'a9e52d92e9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etapes_workflow', sa.Column('signature_cle_stockage', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etapes_workflow', 'signature_cle_stockage')
    # ### end Alembic commands ###
